### ISSUE TITLE
2.0 branch

### ISSUE THREAD

**Issue by ReplicaObscura** [josegonzalez/cakephp-admin#1]
Any plans for a 2.0 branch? I'd be glad to contribute to converting the current code...

**Comment by josegonzalez** [comment]
Yes and no.

# Yes
- If I have CakePHP 2.0 work to do that would benefit from this, it will be one of my top priorities.
- Working on a 2.0 version would be #dagital as hell.
- Certain limitations of 1.x will be removed, and I will be a bit more comfortable using closures etc. to enhance portions such as filtering output

# No
- 1.x doesn't fully work. I don't have the features I want, and I wish to complete those before trying to tackle the issues in a new version of the framework
- None of my current work is 2.0. 2.0 isn't stable. There is no reason for me to move any code to 2.0
- I don't believe there will be many changes that would affect the generated code, but I don't want to tackle them without having a stable api to build upon
- What will happen to the 1.x version? Given that certain things will be different, I do not want to maintain two similar branches.

Feel free to contribute a 2.0 version, but it will not be in master, nor will it be official, until the 1.x branch is complete. I'd honestly rather you help me complete the feature-set in the todo list.

**Comment by ReplicaObscura** [comment]
Thanks for the reply!

I completely understand where you're coming from.

I'll leave as-is for now as cake_admin is more of a "nice to have" in my case, but I think there are several reasons to start porting current plugins to 2.0 now, not the least of which is to have at least a good chunk of a 2.x branch complete by the time CakePHP 2 is officially released. It's gaining popularity quicker since the beta was released, and there's a serious lack of compatible code out there.

The biggest reason not to, of course, is probably that you are still heavily developing the core features of the 1.x branch--thus, I agree and I would be more inclined to help complete the feature-set of the 1.x branch first before contributing an entire 2.x branch which I'd then have to continue to update with your changes to 1.x as they are developed.

That being said, I'd be happy to fork the repo, make a branch, and start implementing some of the features in your todo list. Would that be the best way for me to contribute at this point?

Thanks!

Ben

**Comment by josegonzalez** [comment]
Yes

**Comment by josegonzalez** [comment]
Ported. I'm starting up work again on this, hope we can burn through that backlog :)
