### ISSUE TITLE
Still working on this?

### ISSUE THREAD

**Issue by bobmulder** [josegonzalez/cakephp-admin#2]
Hey Jose,

Are you still working on this project? I am currently building an admin-backend for Cake 3. Maybe you are interested to join?

See ya,

Bob

**Comment by josegonzalez** [comment]
I am no longer working on this project. I recommend you look at [friendsofcake/crud](https://github.com/friendsofcake/crud) and [friendsofcake/crud-view](https://github.com/friendsofcake/crud-view) as a better replacement for this. In fact, in my 2.x book, I use the Crud plugin extensively.

**Comment by bobmulder** [comment]
I know the crud-plugin, but it does not create an admin-section ;) So, when you got ideas, you're welcome ;)

**Comment by josegonzalez** [comment]
The crud-view project is aimed at creating the admin section for you, and is actually based upon some of my work in cakephp-admin (I worked on the initial release of crud-view). I would suggest looking at that project.
